2025-01-15 17:00:15 UTC
Windows-10-10.0.26100
Ren'Py 8.3.4.24120703

Early init took 0.05s
Loading error handling took 0.02s
Loading script took 0.09s
Loading save slot metadata took 0.02s
Loading persistent took 0.00s
Running init code took 0.04s
Loading analysis data took 0.01s
Analyze and compile ATL took 0.00s
Reloading save slot metadata took 0.01s
Index archives took 0.00s
Dump and make backups took 0.04s
Cleaning cache took 0.00s
Making clean stores took 0.00s
Initial gc took 0.04s
DPI scale factor: 1.250000
nvdrs: Loaded, about to disable thread optimizations.
nvdrs: Disabled thread optimizations.
Creating interface object took 0.23s
Cleaning stores took 0.00s
Init translation took 0.03s
Build styles took 0.00s
Load screen analysis took 0.02s
Analyze screens took 0.00s
Save screen analysis took 0.00s
Prepare screens took 0.05s
Save pyanalysis. took 0.00s
Save bytecode. took 0.00s
Running _start took 0.00s
Interface start took 0.12s

Initializing gl2 renderer:
primary display bounds: (0, 0, 1920, 1080)
swap interval: 1 frames
Windowed mode.
Vendor: "b'NVIDIA Corporation'"
Renderer: b'NVIDIA GeForce RTX 4060 Laptop GPU/PCIe/SSE2'
Version: b'4.6.0 NVIDIA 555.97'
Display Info: None
Screen sizes: virtual=(1920, 1080) physical=(1920, 991) drawable=(1920, 991)
Maximum texture size: 4096x4096
Screen sizes: virtual=(1920, 1080) physical=(1920, 991) drawable=(1920, 991)
Maximum texture size: 4096x4096
Screen sizes: virtual=(1920, 1080) physical=(1732, 975) drawable=(1732, 975)
Maximum texture size: 4096x4096

Full traceback:
  File "game/script.rpy", line 29, in script
    n"You've created a new Ren'Py game."
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\ast.py", line 2579, in execute
    Say.execute(self)
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\ast.py", line 621, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\exports\sayexports.py", line 132, in say
    who(what, *args, **kwargs)
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\character.py", line 1438, in __call__
    who = self.prefix_suffix("who", self.who_prefix, who, self.who_suffix)
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\character.py", line 1354, in prefix_suffix
    return (sub(prefix) + sub(body) + sub(suffix))
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\character.py", line 1334, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\substitutions.py", line 373, in substitute
    s = interpolate(s, variables) # type: ignore
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\substitutions.py", line 86, in interpolate
    raise e
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\substitutions.py", line 78, in interpolate
    value = renpy.python.py_eval(code, {}, scope)
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "<none>", line 1, in <module>
NameError: name 'name' is not defined

While running game code:
  File "game/script.rpy", line 29, in script
    n"You've created a new Ren'Py game."
NameError: name 'name' is not defined
Screen sizes: virtual=(1920, 1080) physical=(1920, 991) drawable=(1920, 991)
Maximum texture size: 4096x4096
While handling exception:
Traceback (most recent call last):
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\execution.py", line 599, in run
    node.execute()
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\ast.py", line 2579, in execute
    Say.execute(self)
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\ast.py", line 621, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\exports\sayexports.py", line 132, in say
    who(what, *args, **kwargs)
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\character.py", line 1438, in __call__
    who = self.prefix_suffix("who", self.who_prefix, who, self.who_suffix)
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\character.py", line 1354, in prefix_suffix
    return (sub(prefix) + sub(body) + sub(suffix))
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\character.py", line 1334, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\substitutions.py", line 373, in substitute
    s = interpolate(s, variables) # type: ignore
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\substitutions.py", line 86, in interpolate
    raise e
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\substitutions.py", line 78, in interpolate
    value = renpy.python.py_eval(code, {}, scope)
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "<none>", line 1, in <module>
NameError: name 'name' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\display\error.py", line 140, in report_exception
    renpy.game.invoke_in_new_context(
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\game.py", line 303, in invoke_in_new_context
    return callable(*args, **kwargs)
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\display\error.py", line 48, in call_exception_screen
    return renpy.ui.interact(mouse="screen", type="screen", suppress_overlay=True, suppress_underlay=True)
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\ui.py", line 301, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\display\core.py", line 2215, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\display\core.py", line 3286, in interact_core
    rv = root_widget.event(ev, x, y, 0)
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\display\layout.py", line 1297, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\display\layout.py", line 1297, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\display\layout.py", line 1297, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\display\screen.py", line 791, in event
    rv = self.child.event(ev, x, y, st)
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\display\layout.py", line 1297, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\display\layout.py", line 1526, in event
    rv = super(Window, self).event(ev, x, y, st)
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\display\layout.py", line 285, in event
    rv = d.event(ev, x - xo, y - yo, st)
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\display\layout.py", line 285, in event
    rv = d.event(ev, x - xo, y - yo, st)
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\display\layout.py", line 1297, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\display\layout.py", line 1297, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\display\layout.py", line 1297, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\display\behavior.py", line 1182, in event
    return handle_click(self.clicked)
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\display\behavior.py", line 1103, in handle_click
    rv = run(action)
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\display\behavior.py", line 401, in run
    return action(*args, **kwargs)
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\display\error.py", line 55, in rollback_action
    renpy.exports.rollback(force=True)
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\exports\rollbackexports.py", line 235, in rollback
    renpy.game.log.rollback(checkpoints, greedy=greedy, label=label, force=(force is True), abnormal=abnormal, current_label=current_label)
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\rollback.py", line 930, in rollback
    self.load_failed()
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\rollback.py", line 848, in load_failed
    raise Exception("Couldn't find a place to stop rolling back. Perhaps the script changed in an incompatible way?")
Exception: Couldn't find a place to stop rolling back. Perhaps the script changed in an incompatible way?

Full traceback:
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\main.py", line 652, in main
    run(restart)
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\main.py", line 148, in run
    renpy.execution.run_context(True)
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\execution.py", line 958, in run_context
    context.run()
  File "game/script.rpy", line 29, in script
    n"You've created a new Ren'Py game."
  File "lib/python3.9/future/utils/__init__.py", line 444, in raise_
  File "game/script.rpy", line 29, in script
    n"You've created a new Ren'Py game."
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\ast.py", line 2579, in execute
    Say.execute(self)
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\ast.py", line 621, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\exports\sayexports.py", line 132, in say
    who(what, *args, **kwargs)
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\character.py", line 1438, in __call__
    who = self.prefix_suffix("who", self.who_prefix, who, self.who_suffix)
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\character.py", line 1354, in prefix_suffix
    return (sub(prefix) + sub(body) + sub(suffix))
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\character.py", line 1334, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\substitutions.py", line 373, in substitute
    s = interpolate(s, variables) # type: ignore
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\substitutions.py", line 86, in interpolate
    raise e
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\substitutions.py", line 78, in interpolate
    value = renpy.python.py_eval(code, {}, scope)
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "<none>", line 1, in <module>
NameError: name 'name' is not defined

While running game code:
  File "game/script.rpy", line 29, in script
    n"You've created a new Ren'Py game."
  File "game/script.rpy", line 29, in script
    n"You've created a new Ren'Py game."
NameError: name 'name' is not defined
